version: '3.3'
networks:
  web:
   external: true
services:
    backend:
        image: backend:latest
        container_name: roms-api-backend
        volumes:
          - ./config.yaml:/home/backend/config.yaml
          - ./firebase_credentials.json:/home/backend/firebase_credentials.json
          - ./token.json:/home/backend/token.json
          - ./credentials.json:/home/backend/credentials.json
        networks:
          - web
        labels:
          - "traefik.enable=true"
          - "traefik.backend=api-backend"
          - "traefik.docker.network=web"
          - "traefik.port=3000"
          - "traefik.http.middlewares.api-backend-https-redirect.redirectscheme.scheme=https"
          - "traefik.http.middlewares.api-backend-https-redirect.redirectscheme.permanent=true"
          - "traefik.http.services.api-backend.loadbalancer.server.port=3000"
          - "traefik.http.routers.api-backend.middlewares=api-backend-https-redirect"
          - "traefik.http.routers.api-backend-secure.rule=Host(`YOURDOMAIN`)"
          - "traefik.http.routers.api-backend-secure.tls=true"
          - "traefik.http.routers.api-backend-secure.tls.certresolver=lets-encrypt"
          - "traefik.http.routers.api-backend-secure.service=api-backend"
